#!/bin/bash

python driver.py '_step_ratio = 10' '_enable_multirate = True' '_c_trab = 0.6' 'timestepper_order = 4' '_trab_scheme = "slowest_first_1"' plasma_wave_1D.cpy 'log_file = "TRAB_4/10/plasma_wave_1D_TRAB_4_10.dat"' 'vis_pattern = "TRAB_4/10/plasma_wave_1D-%04d"'
python driver.py '_step_ratio = 20' '_enable_multirate = True' '_c_trab = 0.6' 'timestepper_order = 4' '_trab_scheme = "slowest_first_1"' plasma_wave_1D.cpy 'log_file = "TRAB_4/20/plasma_wave_1D_TRAB_4_20.dat"' 'vis_pattern = "TRAB_4/20/plasma_wave_1D-%04d"' 
python driver.py '_step_ratio = 40' '_enable_multirate = True' '_c_trab = 0.6' 'timestepper_order = 4' '_trab_scheme = "slowest_first_1"' plasma_wave_1D.cpy 'log_file = "TRAB_4/40/plasma_wave_1D_TRAB_4_40.dat"' 'vis_pattern = "TRAB_4/40/plasma_wave_1D-%04d"' 
python driver.py '_step_ratio = 50' '_enable_multirate = True' '_c_trab = 0.6' 'timestepper_order = 4' '_trab_scheme = "slowest_first_1"' plasma_wave_1D.cpy 'log_file = "TRAB_4/50/plasma_wave_1D_TRAB_4_50.dat"' 'vis_pattern = "TRAB_4/40/plasma_wave_1D-%04d"' 
python driver.py '_step_ratio = 100' '_enable_multirate = True' '_c_trab = 0.6' 'timestepper_order = 4' '_trab_scheme = "slowest_first_1"' plasma_wave_1D.cpy 'log_file = "TRAB_4/100/plasma_wave_1D_TRAB_4_100.dat"' 'vis_pattern = "TRAB_4/100/plasma_wave_1D-%04d"'

python driver.py '_step_ratio = 10' '_enable_multirate = True' '_c_trab = 0.4' 'timestepper_order = 5' '_trab_scheme = "slowest_first_1"'  plasma_wave_1D.cpy 'log_file = "TRAB_5/10/plasma_wave_1D_TRAB_5_10.dat"' 'vis_pattern = "TRAB_5/10/plasma_wave_1D-%04d"'    
python driver.py '_step_ratio = 20' '_enable_multirate = True' '_c_trab = 0.4' 'timestepper_order = 5' '_trab_scheme = "slowest_first_1"'  plasma_wave_1D.cpy 'log_file = "TRAB_5/20/plasma_wave_1D_TRAB_5_20.dat"' 'vis_pattern = "TRAB_5/20/plasma_wave_1D-%04d"'    
python driver.py '_step_ratio = 40' '_enable_multirate = True' '_c_trab = 0.4' 'timestepper_order = 5' '_trab_scheme = "slowest_first_1"'  plasma_wave_1D.cpy 'log_file = "TRAB_5/40/plasma_wave_1D_TRAB_5_40.dat"' 'vis_pattern = "TRAB_5/40/plasma_wave_1D-%04d"'    
python driver.py '_step_ratio = 50' '_enable_multirate = True' '_c_trab = 0.4' 'timestepper_order = 5' '_trab_scheme = "slowest_first_1"'  plasma_wave_1D.cpy 'log_file = "TRAB_5/50/plasma_wave_1D_TRAB_5_50.dat"' 'vis_pattern = "TRAB_5/40/plasma_wave_1D-%04d"'    
python driver.py '_step_ratio = 100' '_enable_multirate = True' '_c_trab = 0.4' 'timestepper_order = 5' '_trab_scheme = "slowest_first_1"' plasma_wave_1D.cpy 'log_file = "TRAB_5/100/plasma_wave_1D_TRAB_5_100.dat"' 'vis_pattern = "TRAB_5/100/plasma_wave_1D-%04d"' 

python driver.py '_step_ratio = 10' '_enable_multirate = True' '_c_trab = 0.6' 'timestepper_order = 4'  '_trab_scheme = "fastest_first_1a"' plasma_wave_1D.cpy 'log_file = "TRAB_4/10/ffs/plasma_wave_1D_TRAB_4_10_ffs.dat"' 'vis_pattern = "TRAB_4/10/ffs/plasma_wave_1D-%04d"'   
python driver.py '_step_ratio = 20' '_enable_multirate = True' '_c_trab = 0.6' 'timestepper_order = 4'  '_trab_scheme = "fastest_first_1a"' plasma_wave_1D.cpy 'log_file = "TRAB_4/20/ffs/plasma_wave_1D_TRAB_4_20_ffs.dat"' 'vis_pattern = "TRAB_4/20/ffs/plasma_wave_1D-%04d"'   
python driver.py '_step_ratio = 40' '_enable_multirate = True' '_c_trab = 0.6' 'timestepper_order = 4'  '_trab_scheme = "fastest_first_1a"' plasma_wave_1D.cpy 'log_file = "TRAB_4/40/ffs/plasma_wave_1D_TRAB_4_40_ffs.dat"' 'vis_pattern = "TRAB_4/40/ffs/plasma_wave_1D-%04d"'   
python driver.py '_step_ratio = 50' '_enable_multirate = True' '_c_trab = 0.6' 'timestepper_order = 4'  '_trab_scheme = "fastest_first_1a"' plasma_wave_1D.cpy 'log_file = "TRAB_4/50/ffs/plasma_wave_1D_TRAB_4_50_ffs.dat"' 'vis_pattern = "TRAB_4/40/ffs/plasma_wave_1D-%04d"'   
python driver.py '_step_ratio = 100' '_enable_multirate = True' '_c_trab = 0.6' 'timestepper_order = 4' '_trab_scheme = "fastest_first_1a"' plasma_wave_1D.cpy 'log_file = "TRAB_4/100/ffs/plasma_wave_1D_TRAB_4_100_ffs.dat"' 'vis_pattern = "TRAB_4/100/ffs/plasma_wave_1D-%04d"'

python driver.py '_step_ratio = 10' '_enable_multirate = True' '_c_trab = 0.8' 'timestepper_order = 3' '_trab_scheme = "slowest_first_1"'  plasma_wave_1D.cpy 'log_file = "TRAB_3/10/plasma_wave_1D_TRAB_3_10.dat"' 'vis_pattern = "TRAB_3/10/plasma_wave_1D-%04d"'
python driver.py '_step_ratio = 20' '_enable_multirate = True' '_c_trab = 0.8' 'timestepper_order = 3' '_trab_scheme = "slowest_first_1"'  plasma_wave_1D.cpy 'log_file = "TRAB_3/20/plasma_wave_1D_TRAB_3_20.dat"' 'vis_pattern = "TRAB_3/20/plasma_wave_1D-%04d"'
python driver.py '_step_ratio = 40' '_enable_multirate = True' '_c_trab = 0.8' 'timestepper_order = 3' '_trab_scheme = "slowest_first_1"'  plasma_wave_1D.cpy 'log_file = "TRAB_3/40/plasma_wave_1D_TRAB_3_40.dat"' 'vis_pattern = "TRAB_3/40/plasma_wave_1D-%04d"'
python driver.py '_step_ratio = 50' '_enable_multirate = True' '_c_trab = 0.8' 'timestepper_order = 3' '_trab_scheme = "slowest_first_1"'  plasma_wave_1D.cpy 'log_file = "TRAB_3/50/plasma_wave_1D_TRAB_3_50.dat"' 'vis_pattern = "TRAB_3/40/plasma_wave_1D-%04d"'
python driver.py '_step_ratio = 100' '_enable_multirate = True' '_c_trab = 0.8' 'timestepper_order = 3' '_trab_scheme = "slowest_first_1"' plasma_wave_1D.cpy 'log_file = "TRAB_3/100/plasma_wave_1D_TRAB_3_100.dat"' 'vis_pattern = "TRAB_3/100/plasma_wave_1D-%04d"'


python driver.py '_step_ratio = 10' '_enable_multirate = True' '_c_trab = 0.65' 'timestepper_order = 4' '_trab_scheme = "slowest_first_1"' plasma_wave_1D.cpy 'log_file = "TRAB_4/10/065/plasma_wave_1D_TRAB_4_10.dat"' 'vis_pattern = "TRAB_4/10/065/plasma_wave_1D-%04d"'
python driver.py '_step_ratio = 10' '_enable_multirate = True' '_c_trab = 0.7' 'timestepper_order = 4' '_trab_scheme = "slowest_first_1"' plasma_wave_1D.cpy 'log_file = "TRAB_4/10/070/plasma_wave_1D_TRAB_4_10.dat"' 'vis_pattern = "TRAB_4/10/070/plasma_wave_1D-%04d"'
python driver.py '_step_ratio = 10' '_enable_multirate = True' '_c_trab = 0.75' 'timestepper_order = 4' '_trab_scheme = "slowest_first_1"' plasma_wave_1D.cpy 'log_file = "TRAB_4/10/075/plasma_wave_1D_TRAB_4_10.dat"' 'vis_pattern = "TRAB_4/10/075/plasma_wave_1D-%04d"'
python driver.py '_step_ratio = 10' '_enable_multirate = True' '_c_trab = 0.8' 'timestepper_order = 4' '_trab_scheme = "slowest_first_1"' plasma_wave_1D.cpy 'log_file = "TRAB_4/10/080/plasma_wave_1D_TRAB_4_10.dat"' 'vis_pattern = "TRAB_4/10/080/plasma_wave_1D-%04d"'

